const Usabilla = require('../src/Usabilla')
const buildFakeRequest = require('./helper/FakeRequest')
const Utilities = require('./mock/Utilities')
const UsabillaAPI = require('./mock/UsabillaAPI')

let usabilla, usabillaAPI, utilities

beforeEach(() => {
    utilities = new Utilities()
    usabillaAPI = new UsabillaAPI
    usabilla = new Usabilla({
        Utilities : utilities
    });
    
  });



const usabilla_item = {
    "id": "5e848bc30af8b90316022d7f",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "location": "",
    "date": "2020-04-01T12:40:37.218Z",
    "campaignId": "5e848b61a1f64a5a513cd304",
    "customData": {},
    "data": {
        "Text_area_question": "text area reponse",
        "checkbox_question": [
            "Option_2",
            "Option_3"
        ],
        "drop_down_question": "Option_2",
        "matrix_question": {
            "Question_1": 5,
            "Question_2": 4
        },
        "mood": "2",
        "nps": 9,
        "radio_question": "Option_1",
        "rating_question": 5
    },
    "url": "https://www.uol.com.br/",
    "time": 65003, 
    "cp" : {
        "id": "5e160126d3212c48876eeb59",
        "date": "2020-01-08T16:19:50.646Z",
        "buttonId": "35c9aefa89f9",
        "analyticsId": "6af812165e09",
        "status": "active",
        "name": "Demo - Slide-out Survey Campaign",
        "type": "poll",
        "url": "",
        "button" : {
            "id": "35c9aefa89f9",
            "name": "Demo Button"
        }
    }
}



const dataParsedFromUsabilla =  [
    {
      id: '5de7b281658b765adb62cb44',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-04T13:20:18.688Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'my first feedback',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5de7bb22658b763e6f1d7de6',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-04T13:57:09.306Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'Not good enough. ',
      moodScore: 3,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'my_var',
      ub_answer1: 'example value'
    },
    {
      id: '5dea1dc293906e5c270acd80',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-06T09:22:28.469Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'good',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'my_var',
      ub_answer1: 'example value'
    },
    {
      id: '5dea234c93906e423357eeba',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-06T09:46:07.611Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'test email',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'my_var',
      ub_answer1: 'example value'
    },
    {
      id: '5dee346243a9cb3c9f73a432',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-09T11:48:06.714Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: '<html><br>:)"&amp; <>*çç',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'my_var',
      ub_answer1: 'example value'
    },
    {
      id: '5dfb50e643a9cb366e12b88b',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-19T10:29:11.585Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'test',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'my example test',
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e00c5c2658b765371590a0a',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-23T13:49:03.674Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/category.html',
      comment: 'My comment is here',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'This is another response'
    },
    {
      id: '5e00c5e2658b7678724e9705',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-23T13:49:56.282Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/category.html',
      comment: 'Not good at all',
      moodScore: 1,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'Really bad '
    },
    {
      id: '5e00c600d3212c55c11b9a8b',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-23T13:50:04.827Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/contact.html',
      comment: 'Awesome! love it',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'nooooice'
    },
    {
      id: '5e00c6d793906e53f24ff6e8',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-23T13:53:39.48Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/contact.html',
      comment: 'Another comment here',
      moodScore: 3,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'One more please'
    },
    {
      id: '5e00c79e472ddf09da18e0d2',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-23T13:57:05.612Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/index.html',
      comment: 'One more text here just to say something',
      moodScore: 2,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'please here are some words',
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e00d93bd3212c21ee6f9d17',
      buttonId: 'dbfed44cad75',
      buttonName: 'Secondary Button B',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-23T15:12:07.883Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/contact.html',
      comment: 'test',
      moodScore: 4,
      nps: 3,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e05bbf51a8e9e15ce5bdcc8',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-27T08:08:50.667Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'Test',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'Test',
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e05bc0d1a8e9e1bd2391c0f',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2019-12-27T08:09:10.145Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/category.html',
      comment: 'Test2',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'Test2'
    },
    {
      id: '5e16eb3dd3212c113739f46c',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-09T08:58:48.971Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://safeer2.moe.gov.sa/Portal',
      comment: 'Nice website. ',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e16eb681a8e9e0a2e6ff012',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-09T08:59:31.589Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://safeer2.moe.gov.sa/Portal',
      comment: 'Link is not working',
      moodScore: 3,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e16ee08d3212c2afd7e40b4',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-09T09:10:43.374Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://safeer2.moe.gov.sa/Portal',
      comment: 'Great',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_custom_var_2',
      ub_answer1: '1234'
    },
    {
      id: '5e16ef6393906e1d2239cbd7',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-09T09:16:30.765Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://safeer2.moe.gov.sa/Portal',
      comment: 'Nice',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_custom_var_1',
      ub_answer1: 'abcd',
      ub_question2: 'example_custom_var_2',
      ub_answer2: '1234'
    },
    {
      id: '5e1701da658b761de32af7bf',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-09T10:35:16.431Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://safeer2.moe.gov.sa/Portal/',
      comment: 'Link is not working',
      moodScore: 2,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e1eea5fd3212c05737aad9d',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-15T10:33:17.737Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.veranda-resorts.com/',
      comment: "That's great",
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e1eea7393906e22ef422255',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-15T10:33:38.283Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.veranda-resorts.com/',
      comment: 'Great page',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e1f0471658b765ed63f6669',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-15T12:24:32.281Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.veranda-resorts.com/',
      comment: 'good',
      moodScore: 3,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e1f1077d3212c3cf2568570',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-15T13:15:50.366Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.veranda-resorts.com/',
      comment: 'great',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e1f132d1a8e9e2b5b41e94c',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-15T13:27:24.473Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.veranda-resorts.com/',
      comment: 'link does not worl',
      moodScore: 2,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e2565d2d3212c13d83a4e18',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-20T08:33:30.675Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://outlook.office.com/calendar/view/week',
      comment: 'not working',
      moodScore: 2,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e2567be658b761c26558470',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-20T08:41:41.926Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.google.com/',
      comment: 'Great',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: 'my answer'
    },
    {
      id: '5e28b51d658b76268e21ff41',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-01-22T20:48:47.21Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'top',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'custom_question_exam',
      ub_answer1: 'test',
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e381edbd3212c0cb2636f02',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-03T13:24:04.196Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'ggg',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e38350a658b763e2a3fe71f',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-03T14:58:27.969Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://outlook.office.com/mail/inbox',
      comment: 'nope',
      moodScore: 1,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e3abb5b1a8e9e7a260d24e6',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-05T12:56:04.54Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://outlook.office.com/calendar/view/workweek',
      comment: 'hey testing it with claudia',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4169ac8e28733efc3c5cf6',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-10T14:33:30.154Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://vuejs.org/',
      comment: 'jjjjj',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e416d05e57889165338aca1',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-10T14:47:42.342Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/main',
      comment: 'test',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e417c83203b1240812059b1',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-10T15:53:48.463Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/main',
      comment: 'testing4',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e417cfc67230833863f84a7',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-10T15:55:50.302Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/main',
      comment: 'testing3',
      moodScore: 3,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4554ef6723084ef4665d1f',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-13T13:54:13.127Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.uol.com.br/',
      comment: 'dddd',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4663a3efc5ad149e7f6e7d',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-14T09:09:19.792Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'testing 8',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null,
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e46640c6723086eb478beaf',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-14T09:11:05.585Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'aaaaa',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null,
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e4664ade5788971ac2b7176',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-14T09:13:45.488Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'aaaa',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null,
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e46b91bce0743788f2c83c8',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-14T15:13:43.273Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'aaa',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a611cefc5ad0e1f40a426',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T09:47:18.363Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airportsAAstep2',
      comment: 'ssss',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a61d96723080557121095',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T09:50:27.392Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'sss',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a6381efc5ad167361d514',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T09:57:31.18Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'dddd',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a67d7e5788917ca628aeb',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T10:16:01.133Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'test',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a70af67230811df579bca',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T10:53:46.02Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports',
      comment: 'rrrrr',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a7f14203b120de271af79',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T11:55:10.642Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'hhhh',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a7ff8203b123f294738a1',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T11:58:58.933Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/https%3A%2F%2Fwww.flightright.de%2Fentschaedigung-pruefen%2F%23%2Fflow%2Fairports%23step2',
      comment: 'fffff',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a8250e578892ad903c489',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T12:08:57.446Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/https%3A%2F%2Fwww.flightright.de%2Fentschaedigung-pruefen%2F%23%2Fflow%2Fstandard',
      comment: 'aaa',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a83c6203b121388364066',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T12:15:11.963Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%2523step2',
      comment: 'ssss',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a84ef203b1259230f909a',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T12:20:08.737Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'testttt',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4a86d1e5788948934ec092',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T12:28:11.24Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'yyyyy',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4aa6566723087079319b11',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T14:42:48.935Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/index.html',
      comment: 'Testing',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4aa669203b123a2f07a8df',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T14:43:08.158Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/category.html',
      comment: 'Testing again',
      moodScore: 2,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4ab12be5788970ff1f85dd',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T15:28:52.815Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/managerTrainings',
      comment: 'tesging',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e4ab14d6723086e6a68c7d9',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T15:29:27.228Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/main',
      comment: 'testing',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: 'test'
    },
    {
      id: '5e4ab15defc5ad7fdc10b912',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T15:29:42.235Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/managerForms',
      comment: 'ssss',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4ab16ee578896e722d31a0',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T15:29:59.359Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/managerTrainings',
      comment: 'Testing',
      moodScore: 1,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4ab1a5e578896e7a509168',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-17T15:30:54.423Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/managerTrainings',
      comment: 'test',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4d0447672308763f7fa5f4',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-19T09:48:01.003Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'testing',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4d04968e2873383642d2a8',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-19T09:49:21.343Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'testing',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4d04da672308139462f6df',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-19T09:50:28.061Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'testing',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4d0567ce074306b51ff07f',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-19T09:52:48.925Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'test',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4d0596efc5ad569e621a72',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-19T09:53:36.905Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'ssss',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4d061e203b1219ac40bb5e',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-19T09:55:52.776Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'aaaa',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4d0d00ce074347c761b415',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-19T10:25:17.091Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.flightright.de/entschaedigung-pruefen/#/flow/airports%23step2',
      comment: 'really good',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e4d1ff2ce074332df052c5e',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-19T11:46:03.27Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/managerTrainings',
      comment: 'aaa',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e51690cce07430e8215626e',
      buttonId: '8bb61d5ee0d5',
      buttonName: 'SL - Testing',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-02-22T17:47:02.286Z',
      location: 'The Hague, Netherlands',
      url: 'https://streamlineconsultoria.com.br/#/index/main',
      comment: 'Legal ',
      moodScore: 5,
      nps: 10,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e5f9aefd274637bcd623471',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-04T12:11:36.393Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://epargnant.epsor.fr/',
      comment: 'hahah',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e5f9af8d2746346f359d21a',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-04T12:11:53.663Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://epargnant.epsor.fr/',
      comment: 'heheh',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e789377a1f64a287530b895',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-23T10:46:32.402Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'custom variables',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null,
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e7893c2d6b09b27400aa55c',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-23T10:47:46.28Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'dddd',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null,
      ub_question2: 'my_var',
      ub_answer2: 'example value'
    },
    {
      id: '5e789506d6981d2dcf7f96d7',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-23T10:53:09.95Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'nowww',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e78954ea1f64a28684fb004',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-23T10:54:22.388Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'test 3',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'email',
      ub_answer1: 'someone@gmail.com',
      ub_question2: 'example_question_1',
      ub_answer2: null,
      ub_question3: 'id',
      ub_answer3: '12345'
    },
    {
      id: '5e78978fd27463248761fb5c',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-23T11:03:58.711Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'ddddd',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e7897c8e7703e25094802e2',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-23T11:04:56.897Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'ttttt',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: 'dddd rrrrr'
    },
    {
      id: '5e7898c5a1f64a527d511a81',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-23T11:09:08.651Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'ssss',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: 'qq'
    },
    {
      id: '5e7899e1d2746332347afd63',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-23T11:13:53.025Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: 'here 1',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'advantageCardFlag',
      ub_answer1: 'testing',
      ub_question2: 'example_question_1',
      ub_answer2: null,
      ub_question3: 'fulfilmentType',
      ub_answer3: 1234,
      ub_question4: 'gigyaID',
      ub_answer4: 'test',
      ub_question5: 'loginOption',
      ub_answer5: 'aaa',
      ub_question6: 'pageTemplateID',
      ub_answer6: 'bbb',
      ub_question7: 'pageTemplateType',
      ub_answer7: 'aaa',
      ub_question8: 'previewsPageID',
      ub_answer8: 333
    },
    {
      id: '5e7a96a7a1f64a4deb02b51d',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-24T23:24:52.842Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/single.html',
      comment: 'cordova',
      moodScore: 5,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e7a96bde7703e5eee4e4461',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-24T23:25:14.935Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/single.html',
      comment: '444',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'example_question_1',
      ub_answer1: null
    },
    {
      id: '5e7b2202d6981d51e4260117',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-25T09:19:08.689Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.pearson.com/uk/shop.html',
      comment: 'Pearson test',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e7b221ed6981d2b5c6caf8f',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-25T09:19:35.951Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.pearson.com/uk/shop.html',
      comment: 'link is not working',
      moodScore: 2,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e7b245e44952f16d2064a54',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-25T09:29:12.169Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.pearson.com/uk/shop.html',
      comment: 'Good',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e7b343bd6b09b35a5348bc5',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-25T10:36:53.056Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.pearson.com/uk/shop.html',
      comment: 'not working',
      moodScore: 2,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e7b3520d6981d4f83123699',
      buttonId: '35c9aefa89f9',
      buttonName: 'Demo Button',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-03-25T10:40:42.611Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.pearson.com/uk/shop.html',
      comment: 'demo',
      moodScore: 4,
      nps: 0,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: ''
    },
    {
      id: '5e8488f544952f12f7151ade',
      buttonId: 'a31409d6b75c',
      buttonName: 'Main Button A',
      feedbackType: 'Feedback',
      cpName: '',
      cpAnalyticsId: '',
      date: '2020/01/20',
      date_str: '2020-04-01T12:29:01.784Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.uol.com.br/',
      comment: 'Comment that I would like to share',
      moodScore: 4,
      nps: 9,
      customVariableKey1: '',
      customVariableKey2: '',
      customVariableKey4: '',
      customVariableVal1: '',
      customVariableVal2: '',
      customVariableVal4: '',
      ub_question1: 'choice_element',
      ub_answer1: 'opt2',
      ub_question2: 'please_select_a_subj',
      ub_answer2: 'compliment',
      ub_question3: 'rating_question',
      ub_answer3: '10'
    },
    {
      id: '5dfb856ef6580e031c004df8',
      buttonId: undefined,
      buttonName: 'Main Button A',
      feedbackType: 'Campaign',
      cpName: 'New Slide-out Survey Campaign',
      cpAnalyticsId: 'ec7f50c331b2',
      date: '2020/01/20',
      date_str: '2019-12-19T14:13:04.262Z',
      location: '',
      url: 'https://feedback.cloudwithcoffee.com/about.html',
      comment: '',
      moodScore: '4',
      nps: 9,
      ub_question1: 'Answer',
      ub_answer1: 'Yes',
      ub_question2: 'Rating_custom',
      ub_answer2: 2,
      ub_question3: 'mood',
      ub_answer3: '4',
      ub_question4: 'nps',
      ub_answer4: 9
    },
    {
      id: '5e16ebb96f86da031b012cc6',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Exit Survey Campaign',
      cpAnalyticsId: 'bc5deac98d81',
      date: '2020/01/20',
      date_str: '2020-01-09T09:00:42.88Z',
      location: '',
      url: 'https://safeer2.moe.gov.sa/Portal',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'answer',
      ub_answer1: 'Other',
      ub_question2: 'other',
      ub_answer2: 'I did not find what I was looking for'
    },
    {
      id: '5e16ebdac87d9f03170082d8',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Slide-out Survey Campaign',
      cpAnalyticsId: '6af812165e09',
      date: '2020/01/20',
      date_str: '2020-01-09T09:01:15.567Z',
      location: '',
      url: 'https://safeer2.moe.gov.sa/Portal',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Answer',
      ub_answer1: 'No',
      ub_question2: 'answer',
      ub_answer2: 'Courses'
    },
    {
      id: '5e186dc696ccd50317000337',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Exit Survey Campaign',
      cpAnalyticsId: 'bc5deac98d81',
      date: '2020/01/20',
      date_str: '2020-01-10T12:27:51.125Z',
      location: '',
      url: 'https://www.uol.com.br/',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'What_would_be_a_',
      ub_answer1: '100 euros',
      ub_question2: 'answer',
      ub_answer2: 'Price_is_too_hig'
    },
    {
      id: '5e186def2406bf0315004ea1',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Slide-out Survey Campaign',
      cpAnalyticsId: '6af812165e09',
      date: '2020/01/20',
      date_str: '2020-01-10T12:28:31.968Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.uol.com.br/',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Answer',
      ub_answer1: 'No',
      ub_question2: 'answer',
      ub_answer2: 'Boat',
      customVariableKey1: 'example_custom_var_1',
      customVariableVal1: 'abcd',
      customVariableKey2: 'example_custom_var_2',
      customVariableVal2: '1234'
    },
    {
      id: '5e1c6175bcdd1b031b002a5b',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Air Serbia -  Slide-out Survey Campaign Email',
      cpAnalyticsId: '6650136080b4',
      date: '2020/01/20',
      date_str: '2020-01-13T12:24:21.918Z',
      location: '',
      url: 'https://booking.airserbia.com/dx/JUDX/#/passengers?journeyType=one-way&activeMonth=01-17-2020&pointOfSale=NL&locale=en-US&class=Economy&ADT=1&C13=0&CHD=0&INF=0&origin=BNX&destination=AMS&date=01-16-2020&flight=-477506014&direction=1&execution=e3s1',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Would_you_like_to_receive_our_ne',
      ub_answer1: 'Yes',
      customVariableKey1: 'email',
      customVariableVal1: 'vitor.orlando@usabilla.com'
    },
    {
      id: '5e1d9a26b11386031d00adb6',
      buttonId: undefined,
      buttonName: 'Main Button A',
      feedbackType: 'Campaign',
      cpName: 'Exit Survey A',
      cpAnalyticsId: '8c5e7b510a5a',
      date: '2020/01/20',
      date_str: '2020-01-14T10:38:31.119Z',
      location: '',
      url: '',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'What_would_be_a_',
      ub_answer1: '100',
      ub_question2: 'answer',
      ub_answer2: 'Price_is_too_hig',
      customVariableKey1: 'myname',
      customVariableVal1: 'vitor'
    },
    {
      id: '5e1eeacced476603200004cc',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Slide-out Survey Campaign',
      cpAnalyticsId: '6af812165e09',
      date: '2020/01/20',
      date_str: '2020-01-15T10:34:53.86Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.veranda-resorts.com/',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Answer',
      ub_answer1: 'No',
      ub_question2: 'answer',
      ub_answer2: 'hotel'
    },
    {
      id: '5e1f04a6815a69031b0001e8',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Slide-out Survey Campaign',
      cpAnalyticsId: '6af812165e09',
      date: '2020/01/20',
      date_str: '2020-01-15T12:25:12.119Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.veranda-resorts.com/',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Answer',
      ub_answer1: 'No',
      ub_question2: 'answer',
      ub_answer2: 'rent a car'
    },
    {
      id: '5e1f1371fffb3f0314007448',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Exit Survey Campaign',
      cpAnalyticsId: 'bc5deac98d81',
      date: '2020/01/20',
      date_str: '2020-01-15T13:28:18.408Z',
      location: '',
      url: 'https://www.veranda-resorts.com/',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'What_would_be_a_',
      ub_answer1: '100',
      ub_question2: 'answer',
      ub_answer2: 'Price_is_too_hig'
    },
    {
      id: '5e2727ad807e67031100058c',
      buttonId: undefined,
      buttonName: 'Main Button A',
      feedbackType: 'Campaign',
      cpName: 'New Slide-out Survey Campaign',
      cpAnalyticsId: 'ec7f50c331b2',
      date: '2020/01/20',
      date_str: '2020-01-21T16:32:46.961Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://feedback.cloudwithcoffee.com/',
      comment: '',
      moodScore: '2',
      nps: 9,
      ub_question1: 'Answer',
      ub_answer1: 'Yes',
      ub_question2: 'Rating_custom',
      ub_answer2: 6,
      ub_question3: 'mood',
      ub_answer3: '2',
      ub_question4: 'nps',
      ub_answer4: 9,
      customVariableKey1: 'my_var',
      customVariableVal1: 'example value'
    },
    {
      id: '5e309ef1533470031a0182ef',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Air Serbia -  Slide-out Survey Campaign Email',
      cpAnalyticsId: '6650136080b4',
      date: '2020/01/20',
      date_str: '2020-01-28T20:52:04.856Z',
      location: '',
      url: 'https://booking.airserbia.com/dx/JUDX/#/passengers?journeyType=one-way&activeMonth=01-31-2020&pointOfSale=NL&locale=en-US&class=Economy&ADT=1&C13=0&CHD=0&INF=0&origin=AMS&destination=BEG&date=01-31-2020&flight=1558134552&direction=1',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Would_you_like_to_receive_our_ne',
      ub_answer1: 'Yes',
      customVariableKey1: 'email',
      customVariableVal1: 'aaa@aaa',
      customVariableKey2: 'first_name',
      customVariableVal2: 'test',
      customVariableKey3: 'last_name',
      customVariableVal3: 'test2'
    },
    {
      id: '5e382f4f34b08b0313006787',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Slide-out Survey Campaign',
      cpAnalyticsId: '6af812165e09',
      date: '2020/01/20',
      date_str: '2020-02-03T14:33:53.386Z',
      location: 'Amsterdam, Netherlands',
      url: 'https://www.uol.com.br/',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Answer',
      ub_answer1: 'No',
      ub_question2: 'answer',
      ub_answer2: 'test'
    },
    {
      id: '5e3834a1659f0c031b007492',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Demo - Exit Survey Campaign',
      cpAnalyticsId: 'bc5deac98d81',
      date: '2020/01/20',
      date_str: '2020-02-03T14:56:34.492Z',
      location: '',
      url: 'https://outlook.office.com/mail/inbox',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'What_would_be_a_',
      ub_answer1: 'test campaign',
      ub_question2: 'answer',
      ub_answer2: 'Price_is_too_hig'
    },
    {
      id: '5e39609ddb69a50319007ade',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Air Serbia -  Slide-out Survey Campaign Email',
      cpAnalyticsId: '6650136080b4',
      date: '2020/01/20',
      date_str: '2020-02-04T12:16:30.694Z',
      location: '',
      url: 'https://booking.airserbia.com/dx/JUDX/#/passengers?journeyType=one-way&activeMonth=02-21-2020&pointOfSale=NL&locale=en-US&class=Economy&ADT=1&C13=0&CHD=0&INF=0&origin=AMS&destination=BEG&date=02-21-2020&flight=-1758425510&direction=1&execution=e1s1',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Would_you_like_to_receive_our_ne',
      ub_answer1: 'Yes',
      customVariableKey1: 'email',
      customVariableVal1: 'aaa@gmail',
      customVariableKey2: 'first_name',
      customVariableVal2: 'Vitor',
      customVariableKey3: 'last_name',
      customVariableVal3: 'Orlando'
    },
    {
      id: '5e3a977b32f0260318007804',
      buttonId: undefined,
      buttonName: 'Demo Button',
      feedbackType: 'Campaign',
      cpName: 'Air Serbia -  Slide-out Survey Campaign Email',
      cpAnalyticsId: '6650136080b4',
      date: '2020/01/20',
      date_str: '2020-02-05T10:22:52.267Z',
      location: '',
      url: 'https://booking.airserbia.com/dx/JUDX/#/passengers?journeyType=one-way&activeMonth=02-07-2020&pointOfSale=NL&locale=en-US&class=Economy&ADT=1&C13=0&CHD=0&INF=0&origin=AMS&destination=BEG&date=02-07-2020&flight=-934342190&direction=1&execution=e1s1',
      comment: '',
      moodScore: '',
      nps: '',
      ub_question1: 'Would_you_like_to_receive_our_ne',
      ub_answer1: 'Yes',
      customVariableKey1: 'email',
      customVariableVal1: '',
      customVariableKey2: 'first_name',
      customVariableVal2: '',
      customVariableKey3: 'last_name',
      customVariableVal3: ''
    }
  ]


test('lookUpField in an object', () => {
    expect(usabilla.lookUpField(usabilla_item, ['cp', 'button', 'name'])).toBe(usabilla_item['cp']['button']['name']);
});

test('getDataFromUsabilla', () => {
    const startDate = new Date('2018-07-13T00:00:00Z');
    const endDate = new Date('2018-07-14T00:00:00Z');
    const fields = ['track_name', 'artist'];
    let request = buildFakeRequest({
      startDate,
      endDate,
      fields
    });
    expect(usabilla.getDataFromUsabilla(request)).toStrictEqual(dataParsedFromUsabilla);
});


test('getButtonById', () => {
  expect(usabilla.getButtonById('dbfed44cad75', usabillaAPI.getAllButtons().items)).toEqual({"id": "dbfed44cad75","name": "Secondary Button B"});
});


test('getAllCampaigns', () => {
  expect(usabilla.getButtonById('5de8473843a9cb7b2049e379', usabillaAPI.getAllCampaigns().items)).toEqual({"id": "5de8473843a9cb7b2049e379","date": "2019-12-04T23:54:32.356Z","buttonId": "a31409d6b75c","analyticsId": "8f4860d44341","status": "paused","name": "New Boost Campaign","type": "boost","url": ""});
});